export const LOGIN_SUCCESS = 'LOGIN_SUCCESS',
             LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
             CHANGE_SCENE_TO_MAIN = 'CHANGE_SCENE_TO_MAIN';

export const COLOURS = {
    YELLOW:          '#FFD400', // YELLOW (NCS)
    RED:             '#C1292E', // INTERNATIONAL ORANGE (GOLDEN GATE BRIDGE)
    BLUE:            '#235789', // B'DAZZLED BLUE
    BLACK:           '#161925', // EERIE BLACK
    WHITE:           '#FDFFFC', // BABY POWDER
    LIGHT_BLUE:      '#1BE7FF', // SPANISH SKY BLUE
    LIGHT_GREEN:     '#6EEB83', // VERY LIGHT MALACHITE GREEN
    FACEBOOK_BLUE:   '#4252B2',
};
