export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const COLOURS = {
    YELLOW: '#FFD400', // YELLOW (NCS)
    RED: '#C1292E',    // INTERNATIONAL ORANGE (GOLDEN GATE BRIDGE)
    BLUE: '#235789',   // B'DAZZLED BLUE
    BLACK: '#161925',  // EERIE BLACK
    WHITE: '#FDFFFC',  // BABY POWDER
    FACEBOOK_BLUE: '#4252B2',
};
