# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stinger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stinger
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'React', :path => '../node_modules/react-native'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'StingerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Stinger-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stinger-tvOS

  target 'Stinger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
