# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stinger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stinger
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'StingerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Stinger-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Stinger-tvOS

  target 'Stinger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
